version: '3.9'

networks:
  pgmnetwork:
    driver: bridge
    name: pgmnetwork

services:
  mariadb:
    image: mariadb:10.11
    container_name: pgm_mariadb
    hostname: pgm_mariadb
    networks:
      - pgmnetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: pgm_keycloak
    hostname: pgm_keycloak
    networks:
      - pgmnetwork
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://pgm_mariadb:3306/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    depends_on:
      - mariadb
    command:
      - start-dev

volumes:
  mariadb_data:
    name: mariadb_data